### ISSUE TITLE
Je ne trouve pas le site

### ISSUE THREAD

**Issue by dabrahim** [PapiHack/itDev#1]
Bonjour PapiHack ! Est ce que c'est possible d'avoir le lien de ton site. Merci

**Comment by dabrahim** [comment]
Ça fait un an que je n’ai pas eu de réponse à ça

**Comment by PapiHack** [comment]
Salut, désolé c'est vraiment bizarre mais j'ai pas eu de notif de l'ouverture de cette issue, c'est en fouillant mes anciens repos que je suis tombé dessus. Si tu fais un tour sur mon profil, tu trouveras le lien vers mon site qui se trouve [ici](https://www.itdev.sn).
**PS** : L'ancien n'est plus en ligne, je travaille sur un nouveau.
